Blog App: Integration specs
mahdinoori2000/blog-app pull request #10
Opened 2023-10-24 18:25 UTC by mahdinoori2000

### What is added

- N+1 problem is solved when fetching all posts and their comments for a user.
- Use Capybara to write integration tests for each view in your project.

- [ ] User index page:

- I can see the username of all other users.
- I can see the profile picture for each user.
- I can see the number of posts each user has written.
- When I click on a user, I am redirected to that user's show page.

- [ ] user show page:

- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see the user's bio.
- I can see the user's first 3 posts.
- I can see a button that lets me view all of a user's posts.
- When I click a user's post, it redirects me to that post's show page.
- When I click to see all posts, it redirects me to the user's post's index page.

- [ ]  User post index page:

- I can see the user's profile picture.
- I can see the user's username.
- I can see the number of posts the user has written.
- I can see a post's title.
- I can see some of the post's body.
- I can see the first comments on a post.
- I can see how many comments a post has.
- I can see how many likes a post has.
- I can see a section for pagination if there are more posts than fit on the view.
- When I click on a post, it redirects me to that post's show page.

- [ ]  Post show page:

- I can see the post's title.
- I can see who wrote the post.
- I can see how many comments it has.
- I can see how many likes it has.
- I can see the post body.
- I can see the username of each commentor.
- I can see the comment each commentor left.
- Be sure to include integration specs for any other features you may have implemented!

2023-10-24 19:03 UTC, MahmoudBakr23 requested changes
Hello TEAM 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Well done on writing the tests for both post's `index` and `show` pages
- Descriptive PR and README
- Correct Linters

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers, and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-24 19:03 UTC, MahmoudBakr23 commented on spec/features/users_show_spec.rb
> +end
Well done so far on writing all of your test cases. However, in the user_show_spec page, you still haven't implemented some of the required tests. 🙏 

- [ ] Please write a test that shows the user's first 3 posts
> Note that this tested user should have more than 3 posts to ensure your test works fine when it shows only the first 3 on this user show page.

- [ ] Please write a test that shows the button 'see all posts` for that user
- [ ] For the 3 shown posts on the user show page, please write a test that redirects the user to a post's show page when one of these posts is clicked
- [ ] Please write a test that redirects to the user's post's index page when you click on the see all posts button.

_You can recheck for those requirements starting from this one right [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=I%20can%20see%20the%20user%27s%20first%203%20posts.)._ 🙏

2023-10-25 10:24 UTC, Olamarx requested changes
Hi @badger-99, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media3.giphy.com/media/1O3sFnS78MDxxpmEkq/giphy.gif"/>

 ## Highlights
- Linters passed ✔️
- Most changes fixed ✔️
- Commit messages meaningful ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 10:24 UTC, Olamarx commented on spec/features/users_show_spec.rb
> +  end
- [ ] While you have implemented some of the required changes, I think you forgot to add the last one as observed by the previous reviewer.
![image](https://github.com/mahdinoori2000/blog-app/assets/86200356/c1682979-5a0d-438a-9c7f-a87c38f981ad)

2023-10-25 14:17 UTC, fobadara requested changes
Hi @mahdinoori2000, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.

![REDO](https://user-images.githubusercontent.com/62938735/260208741-25cd532c-dea0-4827-bb4f-5412e8493916.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 14:17 UTC, fobadara commented on spec/features/users_show_spec.rb
[REQUIRED] I can't still see the tests requested by the previous reviewers (Tests that redirect to the post's show page when you click on a user's post). Kindly add this test so that your project can be approved

2023-10-25 15:09 UTC, mahdinoori2000 commented on spec/features/users_show_spec.rb
@fobadara Hello, I added the test for this requirement can you help me with this ? thanks

2023-10-25 16:04 UTC, mahdinoori2000 commented
![review](https://github.com/mahdinoori2000/blog-app/assets/126486418/ca29db9c-20d8-4145-b02b-901ce5e75a6c)

2023-10-25 16:38 UTC, aamirkhan2478 approved these changes
Hi @mahdinoori2000 & @badger-99, 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly :+1: 
✅ No linter error :+1: 
✅ Good commit messages :+1: 
✅ Good descriptive PR :+1: 
✅ Well done :clap: you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 17:04 UTC, merged

2023-10-25 18:05 UTC, nicupop729 reviewed
Hello @mahdinoori2000  👋,

_This is an additional review as a result of the second opinion request._

Please remember that after requesting a second opinion review, we should refrain from asking for another review from the dashboard and wait until the second opinion review is delivered.
The second opinion review in this situation would have saved you from using an extra review attempt if the previous reviewer was wrong to ask for changes again.

Anyway, I am glad the situation was sorted out and that you can advance with your project.

Keep rocking 🚀!

2023-10-25 18:21 UTC, mahdinoori2000 commented
Hello @nicupop729 
Thanks for your consideration but I need to make more progress as my other projects and activities remain. 
I will consider it in the future if I face the same situation. 
Thank you